on: [ push, pull_request ]
jobs:
  build-head:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "10401:5432"
        env:
          POSTGRES_USER: repeater_world_development
          POSTGRES_PASSWORD: te6ahng1phi1uizaeGhahMof1
          POSTGRES_DB: repeater_world_test
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set Up Database Schema
        run: bin/rails db:migrate

      - name: Run Tests
        run: bundle exec rspec

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: head-result
          path: coverage/.resultset.json

  build-base:
    name: "Build base"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "10401:5432"
        env:
          POSTGRES_USER: repeater_world_development
          POSTGRES_PASSWORD: te6ahng1phi1uizaeGhahMof1
          POSTGRES_DB: repeater_world_test
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
        with:
          ## Here we do not checkout the current branch, but we checkout the base branch.
          ref: ${{ github.base_ref }}

      - id: base-ref-commit
        run: echo "REVISION=`git rev-parse HEAD`" >> $GITHUB_STATE

      - id: REVISION
        run: echo $REVISION

      - name: simplecov resultset cache
        id: simplecov-resultset
        uses:  actions/cache@v3
        with:
          path: coverage/.resultset.json
          key: simplecov-resultset-${REVISION}

      - uses: ruby/setup-ruby@v1
        if: steps.simplecov-resultset.outputs.cache-hit != 'true'
        with:
          bundler-cache: true

      - name: Set Up Database Schema
        if: steps.simplecov-resultset.outputs.cache-hit != 'true'
        run: bin/rails db:migrate

      - name: Run Tests
        if: steps.simplecov-resultset.outputs.cache-hit != 'true'
        run: bundle exec rspec

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: base-result
          path: coverage/.resultset.json

  compare:
    name: "Compare base & head coverages"
    runs-on: ubuntu-latest
    needs: [build-base, build-head]

    steps:
      - name: Download base artifact
        uses: actions/download-artifact@v1
        with:
          name: base-result

      - name: Download head artifact
        uses: actions/download-artifact@v1
        with:
          name: head-result

      - uses: kzkn/simplecov-resultset-diff-action@v1
        with:
          base-resultset-path: ./base-result/.resultset.json
          head-resultset-path: ./head-result/.resultset.json
          token: ${{ secrets.GITHUB_TOKEN }}


  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: rake standard
      # TODO: do we want this when we have dependabot?
#      - name: Security audit dependencies
#        run: bin/bundler-audit --update
